export const Errors = {
    INVALID_CREDENTIALS: 'Invalid email or password',
    OTP_MISSING: 'OTP expired or OTP not found',
    DATA_MISSING: 'Data is missing check email , userName and password',
    OTP_VERIFICATION_FAILED: 'Otp verification failed',
    OTP_ERROR: 'Error while sending otp',
    INVALID_OTP: 'Invalid otp ',
    OTP_RESEND_ERROR: 'Error while resending otp',
    INVALID_EMAIL: 'Please provide a valid email',
    PASSWORD_REQUIRED: 'Password requried',
    INVALID_USERDATA: 'Invalid user data ',
    INVALID_DATA: 'Invalid data format',
    OTP_EXPIRED: 'Otp expired or invalid otp',
    TOKEN_EXPIRED: 'Token expired',
    TOKEN_MISMATCH: 'Token not matching ',
    INVALID_PAGINATION_PARAMETERS: 'Invalid pagination parameters',
    FAILED_USER_FETCHING: 'Failed to Fetch Users',
    REFRESH_TOKEN_EXPIRED: 'Refresh Token expired !',
    INVALID_TOKEN: 'Invalid Token !',
    ERROR_IN_LOGOUT: 'Error while logging out !',
    ERROR_CREATING_ACCESS_TOKEN: 'Error while creating access token !',
    ERROR_IN_RESETING_PASSWORD: 'Error while reseting password !',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    AUTHENTICATION_CODE_MISSING: 'Authentication code missing',
    INVALID_ROLE: 'Invalid role !',
    TOKEN_DATA_MISSING: 'Token data is missing',
    INVALID_LOGIN_TYPE: 'Invalid login type',
    PASSWORD_NOT_MATCHING: 'Password not matching',
    UPDATE_FAILED: 'Update failed',
    ACCESS_TOKEN_MISSING: 'Access Token missing !',
    REFRESH_TOKEN_MISSING: 'Refresh Token missing !',
    ACCESS_TOKEN_CREATION_FAILED: 'Failed to create access token',
    REFRESH_TOKEN_CREATION_FAILED: 'Failed to create refresh token',
    ACCESS_TOKEN_SECRETKEY_MISSING: 'Access token secret key not found',
    REFRESH_TOKEN_SECRETKEY_MISSING: 'Refresh token secret key not found',
    FORBIDDEN : 'Not Authorized',
    OTP_MISMATCH : 'OTP does not match',
    CONVERSTION_ERROR : 'Error in file conversion',
    STORAGE_UPLOAD_ERROR : 'Error while uploading file to storage',
    SLOT_NOT_FOUND : 'Slot not found',
    SLOT_ALREADY_BOOKED : 'This slot is already booked',
    SLOT_ALREADY_EXISTS_IN_THAT_TIME : 'Slot already exists in that time',
    VIDEO_CALL_NOT_FOUND : 'Video call not found',
    VIDEO_CALL_NOT_COMPLETED : 'Video call is not completed',
    NOT_ALLOWED : 'You are not allowed to perform this action',
    FEEDBACK_ALREADY_EXISTS : 'Feedback already exists',
    TRAINER_NOT_FOUND : 'Trainer not found',
    
};

export const USER_ERRORS = {
    USER_ALREADY_EXISTS: 'This email is already registered. Please log in instead.',
    USER_INACTIVE: 'User is inactive',
    USER_BLOCKED: 'User is blocked ',
    USER_NOT_FOUND: 'User not found !',
    USER_INVALIDATION: 'Error while validating user !',
    NO_USERS_FOUND: 'No users found',
    UPDATE_FAILED: 'Update failed',
    USER_PROFILE_NOT_FOUND: 'Please complete your profile to continue.',
    USER_GENERATE_WORKOUT_PLAN_FAILED: 'Error while generating workout plan !',
    USER_GENERATE_DIET_PLAN_FAILED: 'Error while generating diet plan !',
    USER_WORKOUT_PLAN_NOT_FOUND: 'Workout plan not found !',
    USER_DIET_PLAN_NOT_FOUND: 'Diet plan not found !',
    NO_ACTIVE_SUBSCRIPTION_FOUND: 'No active subscription found for this user',
    TRAINER_ALREADY_SELECTED: 'You already have an active trainer. Cancel your current trainer before selecting a new one.',
    USER_NOT_SELECTED : 'User is not selected as trainer',
    TRAINER_SELECT_NOT_FOUND : 'Please select to your trainer first',
    TRAINER_SLOT_NOT_FOUND : 'This trainer is not available on this day.',
    SLOT_NOT_FOUND : 'Slot not found',
    CONNOT_BOOK_SLOT_THAT_ALREADY_PASSED : 'Cannot book a slot that has already passed',
    YOUR_HAVE_ALREADY_BOOKED_A_SEESSION_FOR_THIS_DAY : 'You have already booked a session for this day',
    THIS_SLOT_WAS_BOOKED_BY_ANOTHER_USER : 'This slot was just booked by someone else',
    OLD_PASSWORD_INCORRECT : 'The old password you entered is incorrect', 
};


export const TRAINER_ERRORS = {
    TRAINER_ALREADY_EXISTS: 'Trainer already exists',
    INVESTOR_BLOKED: 'Investor is blocked',
    TRAINER_VERIFICATION_FAILED : 'Trainer verification failed',
    TRAINER_VERIFICATION_NOT_FOUND : 'Trainer verification not found',
    TRAINER_NOT_FOUND : 'Trainer not found',
    TRAINER_PROFILE_DATA_NOT_FOUND : 'Trainer profile data not found',
    SLOT_ALREADY_EXISTS_IN_THAT_TIME : 'Slot already exists in that time',
    SLOT_NOT_FOUND : 'Slot not found',
    TRAINER_NOT_SELECTED_IN_THAT_TIME_SLOT : 'Trainer not selected in that time slot',
    YOU_CAN_ONLY_DELETE_YOUR_OWN_SLOT : 'You can only delete your own slot',
    SLOT_ALREADY_BOOKED : 'Cannot delete a slot that has already been booked by a user',
    COULD_NOT_DELETE_SLOT :'Could not delete slot. It may have been booked just now.',
    NO_USERS_SELECTED_YET : 'No users have selected you as their trainer yet.',
};


export const ADMIN_ERRORS = {
    ADMIN_SIGNUP_NOT_ALLOWED: 'You are not allowed to register as admin.',
};

export const SUBSCRIPTION_ERRORS = {
    SUBSCRIPTION_NOT_FOUND: 'Subscription not found',
    SUBSCRIPTION_ALREADY_EXISTS: 'Subscription  already exists',
    SUBSCRIPTION_UPDATE_FAILED: 'Subscription update failed',
    NO_SUBSCRIPTIONS_FOUND: 'No subscriptions found',
    STRIPE_PRICE_ID_MISSING: 'Stripe Price ID is missing for the selected plan',
    MISSING_METADATA: 'Missing metadata in webhook',
    USER_ALREADY_HAS_ACTIVE_MEMBERSHIP: 'User already has an active membership',
};


export const CHAT_ERRORS = {
    CHAT_NOT_FOUND: 'Chat not found',
    MESSAGE_NOT_FOUND: 'Message not found',
    FAILED_FETCHING_CHATS: 'Failed to fetch chats',
    FAILED_FETCHING_MESSAGES: 'Failed to fetch messages',
    ACCESS_DENIED: 'Access Denied: You are not a participant of this chat.',
    YOU_CAN_ONLY_DELETE_YOUR_OWN_MESSAGE: 'You can only delete your own message',
    MESSAGE_ALREADY_DELETED: 'Message already deleted',
};