

export enum NotificationType {
    SLOT_BOOKED = 'SLOT_BOOKED',
    SESSION_CANCELLED = 'SESSION_CANCELLED',
    VERIFICATION_APPROVED = 'VERIFICATION_APPROVED',
    VERIFICATION_REJECTED = 'VERIFICATION_REJECTED',
    PAYMENT_FAILED = 'PAYMENT_FAILED',
    PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
    FEEDBACK_RECEIVED = 'FEEDBACK_RECEIVED',
    SUBSCRIPTION_PURCHASED = 'SUBSCRIPTION_PURCHASED',
    SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
    SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
 
}